name: flutter_rust_http_example
description: "Demonstrates how to use the flutter_rust_http plugin with benchmarking."
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_http:
    path: ../
  dio: ^5.9.0
  syncfusion_flutter_charts: ^30.2.6
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  dio_cache_interceptor: ^4.0.3
  dio_http2_adapter: ^2.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true