[package]
name = "flutter_rust_http"
version = "0.1.0"
edition = "2021"

[lib]
name = "flutter_rust_http"
crate-type = ["cdylib", "staticlib"]

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
bytes = "1.0"
futures = "0.3"
once_cell = "1.10"
parking_lot = "0.12"
libc = "0.2"
log = "0.4"
env_logger = "0.9"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.19", default-features = false }

[build-dependencies]
cbindgen = "0.24"